name: development deploy

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_FOLDER: boocam_wiki-dev

    steps:
      - name: ssh connect & production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          key: ${{ secrets.DEV_SERVER_PASSWORD }}
          port: ${{ secrets.DEV_SERVER_PORT }}
          envs: PROJECT_FOLDER
          script: |
            cd $PROJECT_FOLDER
            git fetch
            git pull origin
            cd client
            npm i
            npm run build
            cd ../server
            npm i
            npm run build
            cd ../docker
            cp -rf nginx-dev nginx/nginx
            docker exec dev-boocam-pm2 pm2 reload /dist/app.js
            docker exec dev-boocam-nginx service nginx reload
